[versions]
# libraries
junit = "4.13.2"
opentest4j = "1.3.0"
okhttp = "4.12.0"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.3.0"
kover = "0.9.3"
qodana = "2025.2.2"
detekt = "1.23.8"
ktlint = "14.0.1"
dependencyCheck = "12.1.9"
forbiddenApis = "3.10"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
dependencyCheck = { id = "org.owasp.dependencycheck", version.ref = "dependencyCheck" }
forbiddenApis = { id = "de.thetaphi.forbiddenapis", version.ref = "forbiddenApis" }
